export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({children}: {children:React.ReactNode}) {
  return (
    <html lang="en">
      <body>
        <header>
          <h3>Header</h3>
        </header>
        {children}
        <footer>
          <h3>Footer</h3>
        </footer>
        
        </body>
    </html>
  );
}
